export const SALON_DETAILS = {
  name: "HABIBS HAIR AND BEAUTY",
  owner: "Anamika",
  category: "Unisex Luxury Beauty Salon",
  address: "AA 3, B 114/115, Uniworld City, Downtown Retail, New Town, West Bengal 700160, India",
  location: "Downtown Mall – New Town",
  phone: "+91 33 4061 5078",
  googleRating: "4.3",
  totalReviews: "115",
  whatsapp: "+913340615078", // Assuming same as phone for now, but usually need a mobile number for WhatsApp
  openingHours: {
    mon: "10:00 AM - 08:30 PM",
    tue: "10:00 AM - 08:30 PM",
    wed: "10:00 AM - 08:30 PM",
    thu: "10:00 AM - 08:30 PM",
    fri: "10:00 AM - 08:30 PM",
    sat: "10:00 AM - 08:30 PM",
    sun: "10:00 AM - 08:30 PM",
  },
};

export const SERVICES = [
  {
    id: "haircuts",
    title: "Haircuts & Styling",
    description: "Expert cuts and styling tailored to your face shape and personality.",
    price: "From ₹800",
    category: "Hair",
    image: "/images/haircut.jpg",
  },
  {
    id: "hair-coloring",
    title: "Hair Coloring",
    description: "Global color, highlights, balayage, and more using premium products.",
    price: "From ₹2500",
    category: "Hair",
    image: "/images/hair-color.jpg",
  },
  {
    id: "hair-treatments",
    title: "Hair Treatments",
    description: "Keratin, Botox, and Spa treatments to restore your hair's natural shine.",
    price: "From ₹3500",
    category: "Hair",
    image: "/images/hair-treatment.jpg",
  },
  {
    id: "nail-extensions",
    title: "Nail Extensions",
    description: "Acrylic and Gel nail extensions for a flawless, long-lasting look.",
    price: "From ₹1500",
    category: "Nails",
    image: "/images/nail-extensions.jpg",
  },
  {
    id: "nail-art",
    title: "Nail Art",
    description: "Creative and intricate designs for your nails by our expert artists.",
    price: "From ₹500",
    category: "Nails",
    image: "/images/nail-art.jpg",
  },
  {
    id: "facials",
    title: "Facials & Skin Care",
    description: "Rejuvenating facials and skin treatments for a radiant glow.",
    price: "From ₹2000",
    category: "Skin",
    image: "/images/facials.jpg",
  },
  {
    id: "grooming",
    title: "Grooming Services",
    description: "Complete grooming services for men and women.",
    price: "From ₹1000",
    category: "Grooming",
    image: "/images/grooming.jpg",
  },
];
